name: functionbeat-testing
on: [push]

jobs:
 push-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repo
      uses: actions/checkout@master

    - name: Download the function beat binary
      run: curl -L -O https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-7.4.1-linux-x86_64.tar.gz && tar xvzf functionbeat-7.4.1-linux-x86_64.tar.gz && mv functionbeat-7.4.1-linux-x86_64 functionbeat && ls -al


    - name: Deploy the functionbeat
      run: ./functionbeat -v -e -d "*" deploy miyazaki-stag-cloudwatch &> /dev/null
      working-directory: functionbeat