name: functionbeat-testing
on: [push]

jobs:
 push-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repo
      uses: actions/checkout@master

    - name: Download the function beat binary
      run: curl -L -O https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-7.4.1-linux-x86_64.tar.gz && tar xvzf functionbeat-7.4.1-linux-x86_64.tar.gz && mv functionbeat-7.4.1-linux-x86_64 functionbeat && ls -al

    - name: Deploy the functionbeat
      continue-on-error: true
      run: ./functionbeat -v -e -d "*" deploy my-fucking-functionbeat-logs
      working-directory: functionbeat

    - name: List the file 
      continue-on-error: true
      run: ls -al
      working-directory: functionbeat